# Generated by Django 3.2.9 on 2021-11-26 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterAlerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributor_id', models.IntegerField()),
                ('title', models.TextField()),
                ('bluejustice_type', models.TextField()),
                ('ecosystem_type', models.TextField()),
                ('impact_type', models.TextField()),
                ('severity', models.TextField()),
                ('magnitude', models.TextField()),
                ('location', models.TextField()),
                ('country', models.TextField()),
                ('status', models.TextField()),
                ('categories', models.TextField()),
                ('description', models.TextField()),
                ('image_url', models.TextField()),
            ],
        ),
    ]
