# Generated by Django 3.2.9 on 2021-11-26 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluejustice_alerts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeralerts',
            name='id',
        ),
        migrations.AddField(
            model_name='registeralerts',
            name='record_id',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
