# Generated by Django 3.2.9 on 2021-11-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluejustice_alerts', '0002_auto_20211125_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeralerts',
            name='bluejustice_type',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='registeralerts',
            name='categories',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='registeralerts',
            name='contributor_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='registeralerts',
            name='country',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='registeralerts',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='registeralerts',
            name='ecosystem_type',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='registeralerts',
            name='image_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='registeralerts',
            name='impact_type',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='registeralerts',
            name='location',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='registeralerts',
            name='magnitude',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='registeralerts',
            name='severity',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='registeralerts',
            name='status',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='registeralerts',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
